### ISSUE TITLE
[BUG]Pictures don't show when adding pictures to an entry

### ISSUE THREAD

**Issue by sstraightea** [MarcDonald/Hibi#42]
When I try to add pictures to an entry the album names are shown, but the images don't load. When I try to select a picture the app crashes when I click on okay after selecting. 
I freshly installed the newest version of the app. 

**Screenshots**
![Screenshot_20200820-005734_Hibi](https://user-images.githubusercontent.com/12102112/90698125-46382f80-e280-11ea-8de1-9b560c7bc018.png)
![Screenshot_20200820-005741_Hibi](https://user-images.githubusercontent.com/12102112/90698128-46d0c600-e280-11ea-8fc2-5ec371c27881.png)

**Device:**
 - Device: Pocophone F1
 - App Version 1.4.0
 - Android Version 9

The error message I'm getting on app crash is the following: 
`time: 1597877878024
msg: java.lang.ClassCastException: android.net.Uri$HierarchicalUri cannot be cast to java.lang.String
stacktrace: java.lang.ClassCastException: android.net.Uri$HierarchicalUri cannot be cast to java.lang.String
	at com.marcdonald.hibi.screens.entries.addentry.AddEntryViewModel$addImages$1.invokeSuspend(AddEntryViewModel.kt:232)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6724)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by MarcDonald** [comment]
Thanks for letting me know, I'll try and take a look at this tomorrow. It's probably related to the version bump of the file picker library that I included in v4.0.0

**Comment by MarcDonald** [comment]
That should be this issue resolved in Version 1.4.1 (https://github.com/MarcDonald/Hibi/releases/tag/v1.4.1%3B37). Thanks for reporting it!
